spring:
  profiles.active: dev

server:
  contextPath: /api
  port: 1231

logging:
  file: vega-account.log
  level:
    org.springframework: INFO

---

spring:
  profiles: dev

  jpa:
    show-sql: true
  datasource:
    data: classpath:/dev/data.sql
  h2:
    console:
      enabled: true

logging:
  level:
    org.apache.catalina: WARN
    org.springframework.security: DEBUG
    org.springframework.boot.test: DEBUG
    org.springframework.test: DEBUG
    org.hibernate.validator: WARN
    eu.socialedge.vega: DEBUG
    org.apache.zookeeper: FATAL
    kafka: FATAL

---

spring:
  profiles: production

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://prod:5432/vega-account
    username: root
    password:
    platform: postgres
    driverClassName: org.postgresql.Driver

logging:
  level:
    eu.socialedge.vega: ERROR
